[package]
name = "playground"
version = "0.1.0"
authors = ["Machtan <jako3047@gmail.com>"]

[dependencies]
froggy = { path = "../../foreign/froggy" }
complecs = { path = "../complecs" }
#error_chain = "0.10"
